name: Vibrant Dental Group
favicon: null
layout_spectrum: 0.51674
typography_spectrum: 0.50585
title: Vibrant Dental Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2a324b'
    - '#fdb943'
    - '#797e8e'
    - '#adafb1'
  brandStrength: 0.3125
  lightness: 0.6140883974730968
  saturation: 0.8821330678183585
  rhythmicContrast: 0.75
purpose: []
